version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bookmanager
      POSTGRES_PASSWORD: password

  backend:
    build: backend
    restart: always
    environment:
      DATABASE_SERVER: db
    ports:
      - 8080:8080

  frontend:
    build: frontend
    restart: always
    ports:
      - 3000:3000
